### PR TITLE
Fix cross validation and various small changes

### PR DESCRIPTION
**Pull request by slundberg**
This primarily is designed to fix nfold_cv(), which is currently broken (now a unit test is there to catch this). It also allows a data matrix to be passed in pre-transposed to avoid extra copying, and fixes/improves the display of feature importances.

### CODE REVIEW

**Comment by tqchen** [comment]
can you check where the test breaks in Travis?

**Comment by slundberg** [comment]
It is an issue with the new nfold_cv() unit test on the nightly build of Julia. I just finished building my own nightly copy, so I'll update with a fix soon.

**Comment by maximsch2** [comment]
An even better thing here might be to use cross-validation utilities from [MLBase.jl](https://github.com/JuliaStats/MLBase.jl) to be more consistent with the broader ecosystem.

**Comment by slundberg** [comment]
@maximsch2 I agree that would be even better. I think that would be best added after this is merged since there are already several changes and fixes in this PR beyond CV. Then the newer MLBase CV methods can be added to an already working starting point.

**Pull request merged**
