### PR TITLE
Update to XGBoost v1.5.2

### PR DESCRIPTION
**Pull request by tylerjthomas9**
All tests pass when I updated XGBoost_jll to v1.5.2

### CODE REVIEW

**Comment by tylerjthomas9** [comment]
The checks are failing on windows and osx, I will look at it more tomorrow when I have access to windows/osx devices.

**Comment by ablaom** [comment]
I see even linux is having issues. 

@ararslan Is travis testing still supported? It seems that travis in this PR thinks the latest julia is 1.5.4.

**Comment by ararslan** [comment]
Using version aliases like `1` in Travis will be outdated because they don't seem to have anyone on their end actively merging and deploying community PRs anymore. `1.x` for some `x` should still work though.

**Comment by ablaom** [comment]
Okay, we've been misled. Github action is already activated but will not run until a maintainer approves the workflow. The problem is that travis has continued to run anyhow, which has confused us. 

So will make a PR to remove travis.

**Comment by ablaom** [comment]
https://github.com/dmlc/XGBoost.jl/pull/106

**Comment by ablaom** [comment]
@tylerjthomas9 You will want to update the GH action test matrix in `.github/workflows/ci.yml` by replacing `1.3` with `1.6`.

**Comment by tylerjthomas9** [comment]
> @tylerjthomas9 You will want to update the GH action test matrix in `.github/workflows/ci.yml` by replacing `1.3` with `1.6`.

Done. Let me know if there is anything else I should add to this PR

**Comment by ablaom** [comment]
@aviks Is there a maintainer who can have a look at this?

**Comment by aviks** [comment]
I merged #106, so this needs a rebase.

**Comment by tylerjthomas9** [comment]
Rebased the PR and replaced the build status icon to the GitHub actions CI status

**Pull request merged**
