### PR TITLE
Fix importance name extraction, add a convenience function

### PR DESCRIPTION
**Pull request by maximsch2**
Regex fixes features like "f0<-1.04" or even "f34<-1.54e-5" which were incorrectly handled before. Also adds a new function that takes a set of feature names to make interpreation easier without dealing with feature map files.

### CODE REVIEW

**Comment by slundberg** [comment]
I originally wrote that regexp, thanks for the fix!

**Comment by slundberg** [comment]
I should also note that the Base.display functions need to be replaced with Base.show and Base.writemime after this is merged.

**Comment by maximsch2** [comment]
Agreed. While we are on that topic, I'll propose setting silent=1 by default everywhere as well.

Another cool thing would be automatically handling custom objective function gradient and hessian using ForwardDiff.jl. Given its performance, Julia might be the best language to actually write custom objectives for XGBoost for those who don't want to deal with C++.

**Comment by maximsch2** [comment]
Pinging @antinucleon. Can you please review this and #19 ?

**Pull request merged**
